"""empty message

Revision ID: 190eff5397a2
Revises: bc7c99ae0908
Create Date: 2025-02-11 17:58:49.266543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190eff5397a2'
down_revision: Union[str, None] = 'bc7c99ae0908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('events_name_event_key', 'events', type_='unique')
    op.create_unique_constraint(None, 'events', ['name'])
    op.drop_column('events', 'name_event')
    op.add_column('members', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('members_user_name_key', 'members', type_='unique')
    op.create_unique_constraint(None, 'members', ['name'])
    op.drop_column('members', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='unique')
    op.create_unique_constraint('members_user_name_key', 'members', ['user_name'])
    op.drop_column('members', 'name')
    op.add_column('events', sa.Column('name_event', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='unique')
    op.create_unique_constraint('events_name_event_key', 'events', ['name_event'])
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
