"""empty message

Revision ID: 6de3fac68b96
Revises: fdd3251b073b
Create Date: 2025-02-04 19:29:31.803204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de3fac68b96'
down_revision: Union[str, None] = 'fdd3251b073b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_event', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_event')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game')
    op.drop_table('member')
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('event_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='event_pkey'),
    sa.UniqueConstraint('name', name='event_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('member_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gameWin', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='member_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='member_pkey'),
    sa.UniqueConstraint('name', name='member_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], name='game_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_pkey'),
    sa.UniqueConstraint('name', name='game_name_key')
    )
    op.drop_table('members')
    op.drop_table('events')
    # ### end Alembic commands ###
