"""empty message

Revision ID: a7f536aa69f0
Revises: a5f685729bd2
Create Date: 2025-02-25 17:52:59.478858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f536aa69f0'
down_revision: Union[str, None] = 'a5f685729bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eventmember_member_id_fkey', 'eventmember', type_='foreignkey')
    op.drop_constraint('eventmember_event_id_fkey', 'eventmember', type_='foreignkey')
    op.create_foreign_key(None, 'eventmember', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'eventmember', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('games_user_id_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_event_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'games', 'members', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_event_id_fkey', 'games', 'events', ['event_id'], ['id'])
    op.create_foreign_key('games_user_id_fkey', 'games', 'members', ['user_id'], ['id'])
    op.drop_constraint(None, 'eventmember', type_='foreignkey')
    op.drop_constraint(None, 'eventmember', type_='foreignkey')
    op.create_foreign_key('eventmember_event_id_fkey', 'eventmember', 'events', ['event_id'], ['id'])
    op.create_foreign_key('eventmember_member_id_fkey', 'eventmember', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###
