"""empty message

Revision ID: a80b29f315ef
Revises: 3a802525b70e
Create Date: 2025-02-05 16:08:08.840345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80b29f315ef'
down_revision: Union[str, None] = '3a802525b70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmember',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'member_id')
    )
    op.drop_table('event_member_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_member_association',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_member_association_event_id_fkey'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='event_member_association_member_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', 'member_id', name='event_member_association_pkey')
    )
    op.drop_table('eventmember')
    # ### end Alembic commands ###
