"""empty message

Revision ID: b9f9de557196
Revises: a80b29f315ef
Create Date: 2025-02-05 17:39:30.352818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f9de557196'
down_revision: Union[str, None] = 'a80b29f315ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'gameWin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'gameWin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
