"""empty message

Revision ID: bc7c99ae0908
Revises: e1daa92f9396
Create Date: 2025-02-11 17:55:17.187692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7c99ae0908'
down_revision: Union[str, None] = 'e1daa92f9396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_event', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('end_event', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_event')
    op.drop_column('events', 'start_event')
    # ### end Alembic commands ###
