"""empty message

Revision ID: e6c8f58135b7
Revises: 1dac06b42d40
Create Date: 2025-03-18 15:02:08.706742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c8f58135b7'
down_revision: Union[str, None] = '1dac06b42d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('steam_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'members', ['steam_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_column('members', 'steam_id')
    # ### end Alembic commands ###
