"""empty message

Revision ID: fdee70870b1c
Revises: 190eff5397a2
Create Date: 2025-02-11 17:59:34.420652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdee70870b1c'
down_revision: Union[str, None] = '190eff5397a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('games', 'name_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name_game', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('games', 'name')
    # ### end Alembic commands ###
